import type { MdxBlockType } from "./mdx-blocks";

export const BLOCK_TYPE_LABELS: Record<MdxBlockType, string> = {
  paragraph: "Text",
  heading: "Heading",
  image: "Image",
  quote: "Quote",
  list: "List",
  todo: "To-do list",
  toggle: "Toggle",
  table: "Table",
  bookmark: "Bookmark",
  embed: "Embed",
  file: "File",
  "page-link": "Page link",
  "news-block": "News",
  "publications-block": "Publications",
  "works-block": "Works",
  "teaching-block": "Teaching",
  "hero-block": "Hero",
  "link-list-block": "Link list",
  "featured-pages-block": "Featured pages",
  columns: "Columns",
  column: "Column",
  "news-entry": "News entry",
  "works-entry": "Works entry",
  "teaching-entry": "Teaching entry",
  "publications-entry": "Publication",
  "teaching-links": "Teaching links",
  "publications-profile-links": "Profile links",
  divider: "Divider",
  callout: "Callout",
  code: "Code",
  raw: "Raw MDX",
};
